const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('api', {
    verElectron: () => process.version.electron,
    abrirJanelaInicio: () => ipcRenderer.send('abrir-janela-inicio'),
    abrirJanelaLogin: () => ipcRenderer.send('abrir-janela-login'),
    buscarUsuarios: () => ipcRenderer.invoke('buscar-usuarios'),
    validarLogin: (login, senha) => ipcRenderer.invoke('validar-login', login, senha),
    totalUsuarios: () => ipcRenderer.invoke('total-usuarios'),
    totalONGs: () => ipcRenderer.invoke('total-ongs'),
    totalServicos: () => ipcRenderer.invoke('total-servicos'),
    totalHoras: () => ipcRenderer.invoke('total-horas'),
    totalUsuariosInativos: () => ipcRenderer.invoke('total-usuarios-inativos'),
    totalPontos: () => ipcRenderer.invoke('total-pontos'),
    totalONGsInativas: () => ipcRenderer.invoke('total-ongs-inativas'),
    totalPremium: () => ipcRenderer.invoke('total-premium'),
    totalServicosCadastrados: () => ipcRenderer.invoke('total-servicos-cadastrados'),
    totalSolicitacoesAceitas: () => ipcRenderer.invoke('total-solicitacoes-aceitas'),
    totalSolicitacoesPendentes: () => ipcRenderer.invoke('total-solicitacoes-pendentes'),
    totalSolicitacoesRecusadas: () => ipcRenderer.invoke('total-solicitacoes-recusadas'),
    editarUsuario: (cpf, ativo, pontos, horas) => ipcRenderer.invoke('alterar-usuario', { cpf, ativo, pontos, horas }),
    buscarONGs: () => ipcRenderer.invoke('buscar-ongs'),
    editarONG: (cnpj, ativo, responsavel, foco) => ipcRenderer.invoke('alterar-ong', { cnpj, ativo, responsavel, foco }),
    mediaNotas: () => ipcRenderer.invoke('media-notas'),
    buscarServicos: () => ipcRenderer.invoke('buscar-servicos'),
    editarServico: (cod, ativo, horas, foco, nota) => ipcRenderer.invoke('alterar-servico', { cod, ativo, horas, foco, nota }),
    buscarSolicitacoes: () => ipcRenderer.invoke('buscar-solicitacoes'),
    editarSolicitacao: (cod, statusS, statusE, pontos) => ipcRenderer.invoke('alterar-solicitacao', { cod, statusS, statusE, pontos }),
    cadastrarUsuario: (usuario) => ipcRenderer.invoke('cadastrar-usuario', usuario),
    buscarPremium: () => ipcRenderer.invoke('buscar-premium'),
    totalPremiumGeral: () => ipcRenderer.invoke('total-premium-geral'),
    totalAtrasadas: () => ipcRenderer.invoke('total-atrasadas'),
    totalReceita: () => ipcRenderer.invoke('total-receita'),
})