// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBATef1Aj-5UH29qhvQJJabITuEdCxNiw8',
    appId: '1:448094336267:web:c9a0bb2efde633d98b5e0e',
    messagingSenderId: '448094336267',
    projectId: 'mutuo-44e7e',
    authDomain: 'mutuo-44e7e.firebaseapp.com',
    storageBucket: 'mutuo-44e7e.firebasestorage.app',
    measurementId: 'G-39YWV4CG62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy4w1jruaBsmF6F9OAfkD60cQmuz5z_sA',
    appId: '1:448094336267:android:7664c3e796c663628b5e0e',
    messagingSenderId: '448094336267',
    projectId: 'mutuo-44e7e',
    storageBucket: 'mutuo-44e7e.firebasestorage.app',
  );
}
